"""
Django settings for example project.

Generated by 'django-admin startproject' using Django 1.9.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""



#// Django for Android
#$color-primary: $palette-light-green-500 !default;
#$color-primary-dark: $palette-light-green-700 !default;
#$color-accent: $palette-light-green-800 !default;


import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'i527ga%pzodwg@6w+*+5rf#i_v#-we1%g=0i=b2fx=ys52&+dx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'djangoforandroid.builder',
    'djangoforandroid.framework'

#    'djangoforandroid.d4a', #optional
#    'djangoforandroid.mdl', #optional

]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'example.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR, "templates"),],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': True,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'example.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'


STATIC_ROOT = os.path.join(BASE_DIR, 'apk_resources')


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]


ANDROID = {

    'APK': {
        'name': "Django for Android",
        'version': '0.6',
        'numericversion': 60,
        'package': 'com.yeisoncardona.djangoforandroid',
        'icon': os.path.join(BASE_DIR, 'static', 'images', 'icon.png'),
        'statusbarcolor': '#689F38',
        'navigationbarcolor': '#689F38',
        'orientation': 'sensor',
    },


    'BUILD': {
        'exclude_dirs': ['djangoforandroid', 'pythonforandroid'],
        'include_exts': ['py', 'png', 'sqlite3', 'html', 'css', 'js', 'svg', 'ttf', 'eot', 'woff', 'woff2', 'otf'],
        },

    'ANDROID': {
        'ARCH': 'armeabi-v7a',
        'SDK': '/opt/android-sdk',
        'API': '21',
        'CRYSTAX_NDK': '/opt/crystax-ndk-10.3.2',
        'CRYSTAX_NDK_VERSION': '10.3.2',
    },

    'SPLASH': {
        'static_html': os.path.join(BASE_DIR, 'templates', 'splash.html'),
        'resources': [os.path.join(BASE_DIR, 'static', 'images', 'background.png'),],
    },

    'KEY': {
        'RELEASE_KEYSTORE': os.path.join(BASE_DIR, 'd4a.keystore'),
        'RELEASE_KEYALIAS': 'd4a',
        'RELEASE_KEYSTORE_PASSWD': 'passwd',
        'RELEASE_KEYALIAS_PASSWD': 'passwd',
    },


}
